#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-squid-update event
#--------------------------------------------------

my $event = "nethserver-squid-update";

event_actions($event, qw(
   initialize-default-databases 00
   nethserver-squid-conf 20
));

templates2events("/etc/squid/squid.conf",  $event);
templates2events("/etc/squid/acls/no_cache.acl",  $event);
templates2events("/etc/squid/acls/ssl_bypass.acl",  $event);
templates2events("/etc/dnsmasq.conf",  $event);
templates2events("/etc/hosts",  $event);
templates2events("/var/www/html/wpad.dat",  $event);
templates2events("/etc/sysconfig/squid",  $event);
event_services($event, 'squid' => 'restart');
event_services($event, 'httpd' => 'reload');
event_services($event, 'dnsmasq' => 'reload');

#--------------------------------------------------
# actions for nethserver-squid-save event
#--------------------------------------------------

my $event = "nethserver-squid-save";

event_actions($event, qw(
   firewall-adjust 30
));

templates2events("/etc/squid/squid.conf",  $event);
templates2events("/etc/squid/acls/no_cache.acl",  $event);
templates2events("/etc/squid/acls/ssl_bypass.acl",  $event);
templates2events("/etc/dnsmasq.conf",  $event);
templates2events("/etc/hosts",  $event);
templates2events("/var/www/html/wpad.dat",  $event);
templates2events("/etc/sysconfig/squid",  $event);
event_services($event, 'squid' => 'restart');
event_services($event, 'httpd' => 'reload');
event_services($event, 'dnsmasq' => 'reload');

#
# nethserver-samba-{save,update,adsjoin) events
#
foreach (qw(
    nethserver-samba-save
    nethserver-samba-update
    nethserver-samba-adsjoin
)) {
    event_templates($_, qw(
        /etc/squid/squid.conf
        /etc/sysconfig/squid
    ));
    event_services($_, qw(
       squid restart
    ));
}

#
# Invalidate credentials cache when user account state changes
#
foreach (qw(
    password-modify
    user-lock
    user-unlock
)) {
    event_services($_, qw(
       squid reload
));
}
