#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

my $input = readInput();
my $cmd = $input->{'action'};

if ($cmd eq 'configuration') {
    my $db = esmith::ConfigDB->open();
    foreach (qw(Lists CustomListURL)) {
        $db->set_prop('squidguard', $_, $input->{$_});
    }
    system("/sbin/e-smith/signal-event -j nethserver-squidguard-downloadlists");
} elsif ($cmd eq 'update-category') {
    my $db = esmith::ConfigDB->open('contentfilter');
    $db->set_prop($input->{'name'}, 'Description', $input->{'Description'});
    $db->set_prop($input->{'name'}, 'Domains', join(",",@{$input->{'Domains'}}));
    system("/sbin/e-smith/signal-event -j nethserver-squidguard-save");
} else {
    error();
}
