#!/usr/bin/php
<?php
/*
 * Copyright (C) 2019 Nethesis S.r.l.
 * http://www.nethesis.it - nethserver@nethesis.it
 *
 * This script is part of NethServer.
 *
 * NethServer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or any later version.
 *
 * NethServer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NethServer.  If not, see COPYING.
*/


require_once("/usr/libexec/nethserver/api/lib/Helpers.php");

$data = readInput();

$v = new LegacyValidator($data);
$sdb = new EsmithDatabase('squid');

if ($data['action'] == 'update') {
    if (!$sdb->getKey($data['name'])) {
        $v->addValidationError('name', 'rule_not_found');
    }

}

$v_domain = $v->createValidator()->hostname(1);
if(isset($data['Dst']) && $data['Dst']) {
    foreach ($data['Dst'] as $d){
        if( ! $v_domain->evaluate($d)) {
            $report->addValidationError('Dst', $v_domain);
        }
    }
}

# Validate the input
if ($v->validate()) {
    success();
} else {
    error($v);
}
