#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

my $input = readInput();
my $cmd = $input->{'action'};

if ($cmd eq 'configuration') {
    my $db = esmith::ConfigDB->open();
    foreach (qw(status PortBlock ParentProxy GreenMode BlueMode PortRedirect)) {
        $db->set_prop('squid', $_, $input->{$_});
    }
    $db->set_prop('squid', 'SafePorts', join(',',@{$input->{'SafePorts'}}));

    system("/sbin/e-smith/signal-event -j nethserver-squid-save");
} elsif ($cmd eq 'update-bypass') {
    my $db = esmith::ConfigDB->open('fwrules');
    $db->set_prop($input->{'name'}, 'Description', $input->{'Description'});

    if ($input->{'Domains'}) {
        $db->set_prop($input->{'name'}, 'Domains', join(",", @{$input->{'Domains'}}));
    }
    if ($input->{'Host'}) {
        $db->set_prop($input->{'name'}, 'Host', $input->{'Host'}{'type'}.";".$input->{'Host'}{'name'});
    }

    system("/sbin/e-smith/signal-event -j firewall-adjust");
} elsif ($cmd eq 'enable-bypass' || $cmd eq 'disable-bypass') {
    my $db = esmith::ConfigDB->open('fwrules');
    my $status =( $cmd eq 'enable-bypass') ? 'enabled' : 'disabled';
    $db->set_prop($input->{'name'}, 'status', $status);

    system("/sbin/e-smith/signal-event -j firewall-adjust");
} else {
    error();
}
