#!/bin/bash

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#


# Re-initialize the kerberos keytab, if we are joined to Active Directory:
smbads=/usr/libexec/nethserver/smbads
if [ -x ${smbads} ] && ${smbads} test; then
    /usr/libexec/nethserver/smbads initkeytab
fi

# Initialize SSL db
/etc/e-smith/events/actions/nethserver-squid-init-ssldb

# Delete unused ACL, can be removed in the future. Refs #2973
rm -f /etc/squid/no-cache

# Publish certificate for clients
ln -sf /etc/pki/tls/certs/NSRV.crt /var/www/html/proxy.crt

exit 0
