#!/bin/bash

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
CACHE_STATUS=`/sbin/e-smith/config getprop squid DiskCache`

if [ "$CACHE_STATUS" = "enabled" ]; then
  if [ ! -f "/var/spool/squid/swap.state" ]; then
      service squid status >/dev/null && service squid stop
      squid -z -F -N
  fi
fi

exit 0
